"""Added todoentry table

Revision ID: 1de1facccd39
Revises: 6e78c6a8f347
Create Date: 2023-08-13 17:30:05.083598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de1facccd39'
down_revision: Union[str, None] = '6e78c6a8f347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todoentry_id'), 'todoentry', ['id'], unique=False)
    op.create_index(op.f('ix_todoentry_key'), 'todoentry', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todoentry_key'), table_name='todoentry')
    op.drop_index(op.f('ix_todoentry_id'), table_name='todoentry')
    op.drop_table('todoentry')
    # ### end Alembic commands ###
