"""FAS-45 : update entry col name from key

Revision ID: 719b0fa26dbd
Revises: f2e9bdeb9998
Create Date: 2023-10-04 18:06:34.117772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719b0fa26dbd'
down_revision: Union[str, None] = 'f2e9bdeb9998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_entries', sa.Column('entry', sa.String(length=256), nullable=True))  # noqa: E501
    op.drop_index('ix_todo_entries_key', table_name='todo_entries')
    op.create_index(op.f('ix_todo_entries_entry'), 'todo_entries', ['entry'], unique=True)  # noqa: E501
    op.drop_column('todo_entries', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_entries', sa.Column('key', sa.VARCHAR(length=256), nullable=True))  # noqa: E501
    op.drop_index(op.f('ix_todo_entries_entry'), table_name='todo_entries')
    op.create_index('ix_todo_entries_key', 'todo_entries', ['key'], unique=False)  # noqa: E501
    op.drop_column('todo_entries', 'entry')
    # ### end Alembic commands ###
