"""sqlalchemy2.0 updates

Revision ID: f2e9bdeb9998
Revises: 1de1facccd39
Create Date: 2023-09-29 20:26:56.276020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e9bdeb9998'
down_revision: Union[str, None] = '1de1facccd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_entries_id'), 'todo_entries', ['id'], unique=False)
    op.create_index(op.f('ix_todo_entries_key'), 'todo_entries', ['key'], unique=True)
    op.drop_index('ix_todoentry_id', table_name='todoentry')
    op.drop_index('ix_todoentry_key', table_name='todoentry')
    op.drop_table('todoentry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoentry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=256), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_todoentry_key', 'todoentry', ['key'], unique=False)
    op.create_index('ix_todoentry_id', 'todoentry', ['id'], unique=False)
    op.drop_index(op.f('ix_todo_entries_key'), table_name='todo_entries')
    op.drop_index(op.f('ix_todo_entries_id'), table_name='todo_entries')
    op.drop_table('todo_entries')
    # ### end Alembic commands ###
